CREATE OR REPLACE PROCEDURE ALJOLANDA_PR_FACTORIAL_2(ERRBUF OUT VARCHAR2, RETCODE OUT NUMBER, N NUMBER) IS
    S NUMBER := N;
    RES NUMBER := N;
    FACT_1 EXCEPTION;
    FACT_0 EXCEPTION;
BEGIN
    If S = 0 OR S = 1 THEN 
        RAISE FACT_1;
    ELSIF S < 0 THEN 
        RAISE FACT_0;
    END IF;
    
    LOOP
        S := S - 1;
        RES := RES * S;
        EXIT WHEN S = 1;
    END LOOP;
    FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'FACTORIAL = ' || RES);
EXCEPTION
    WHEN FACT_1 THEN 
        FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'FACTORIAL = 1');
    WHEN FACT_0 THEN
        FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'Input Cannot Be Less Than 0!');
    WHEN NO_DATA_FOUND THEN
        FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'Input a Number to Compute Factorial!');
    WHEN OTHERS THEN 
        FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'Check Your Program!');
END;
/

SET SERVEROUTPUT ON;

EXEC ALJOLANDA_PR_FACT(5);