-- Procedure
PROCEDURE ALJOLANDA_PR_TEST (ERRBUF OUT VARCHAR2, RETCODE OUT NUMBER)
IS
BEGIN
    FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'WELCOME TO ORACLE EBS PROCEDURE!');
END;
/

-- Function 
FUNCTION ALJOLANDA_FN_TEST  RETURN VARCHAR2 IS V_MSG VARCHAR2(2000);
BEGIN
    V_MSG := 'WELCOME TO ORACLE EBS FUNCTION!';
    RETURN V_MSG;
END;
/